version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://fivjourney_user:fivjourney_pass@db:5432/fivjourney_tools
      - SECRET_KEY=dev-secret-key-change-in-production
      - DEBUG=True
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=fivjourney_tools
      - POSTGRES_USER=fivjourney_user
      - POSTGRES_PASSWORD=fivjourney_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: 